<?php

namespace App\Http\Controllers\Dashboard\Fordeal;

use App\Http\Controllers\Dashboard\EmployeeController;
use Illuminate\Http\Request;
use Illuminate\View\View;


class FordealEmployeeController extends EmployeeController
{
    public function create($view = null, $data = null)
    {
        return parent::create('dashboard.fordeal.employees.create'); // TODO: Change the autogenerated stub
    }


}
